version: '3.7'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: 'postgresql://user:password@db:5432/tasks_db'
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
